runtime: nodejs
env: flex

manual_scaling:
  instances: 1
resources:
  cpu: 1
  memory_gb: 0.5
  disk_size_gb: 10

env_variables:
  NODE_ENV: production
  #sql database connection variables
  SQL_USER: huhu
  SQL_PASSWORD: password
  SQL_DATABASE: ecs193_database
  # e.g. my-awesome-project:us-central1:my-cloud-sql-instance
  INSTANCE_CONNECTION_NAME: majestic-legend-193620:us-west1:test-database
  CLIENT_ID: 671445578517-ogrl80hb1pnq5ruirarvjsmvd8th2hjp.apps.googleusercontent.com
  CLIENT_WEB_SECRET: K6gGjixzDWcT18inlGLnydQv
  CLIENT_ELEC_ID: 671445578517-io87npos82nmk6bk24ttgikc9h4uls4l.apps.googleusercontent.com
  #MailJet api keys
  MAILJET_PUBLIC: 524c051f4fb254ae5636592655d92194
  MAILJET_PRIVATE: 0b74bf7ddd333cad1d75c2dd2570cd7a


beta_settings:
  # The connection name of your instance, available by using
  # 'gcloud beta sql instances describe [INSTANCE_NAME]' or from
  # the Instance details page in the Google Cloud Platform Console.
  cloud_sql_instances: majestic-legend-193620:us-west1:test-database